apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: shoppingapi
    tags.datadoghq.com/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: shoppingapi
        tags.datadoghq.com/version: v1
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: v2.32.0
    spec:
      containers:
        - name: shoppingapi
          image: nmhieuit/shoppingapi:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_SAMPLE_RATE
              value: "0.5"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  type: LoadBalancer
  selector:
    app: shoppingapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      # nodePort: 31000
