version: '3.4'

services:
  shopping.api:
    container_name: shoppingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://shoppingdb:27017"
      - DD_ENV=Development
      - DD_SERVICE=shoppingclient
      - DD_VERSION=v1
      - DD_LOGS_INJECTION=true
      - DD_TRACE_SAMPLE_RATE=0.5
    depends_on:
      - shopping.db
    ports:
      - "8000:80"

  shopping.client:
    container_name: shoppingclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ShoppingAPIUrl=http://shoppingapi
      - DD_ENV=Development
      - DD_SERVICE=shoppingclient
      - DD_VERSION=v1
      - DD_LOGS_INJECTION=true
      - DD_TRACE_SAMPLE_RATE=0.5
    depends_on:
      - shopping.db
      - shopping.api
    labels:
      - com.datadoghq.tags.env=dev
      - com.datadoghq.tags.service=shoppingclient
      - com.datadoghq.tags.version=v1
    ports:
      - "8001:80"

  shopping.db:
    container_name: shoppingdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
