- hosts: kubernetes
  # become: true
  user: ansadmin

  tasks:
  - name: create a deployment
    command: kubectl apply -f /home/ansadmin/run-devops/k8s/shoppingclient.yaml

  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.apps/shoppingclient-deployment