- hosts: localhost
  become: true
  tasks:

  - name: rebuild docker images
    command: docker-compose -f /home/ansadmin/Shopping/docker-compose.yml -f /home/ansadmin/Shopping/docker-compose.override.yml build

  - name: create docker container
    command: docker-compose -f /home/ansadmin/Shopping/docker-compose.yml -f /home/ansadmin/Shopping/docker-compose.override.yml up -d

  - name: tag docker image
    command: docker tag shoppingclient:latest nmhieuit/shoppingclient:latest

  - name: login docker hub
    command: docker login -u nmhieuit -p Hieu@1983

  - name: push docker image
    command: docker push nmhieuit/shoppingclient:latest